### ISSUE TITLE
List Index Out Of Range | Extract.py | line 58 and 65

### ISSUE THREAD

**Issue by kwidyas** [onlyphantom/emailnetwork#10]
I got issue when calling this code :

print(f'{len(reader)} emails in the sample mbox.')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/karinawidyastuti/trial/lib/python3.8/site-packages/emailnetwork/extract.py", line 58, in __len__
    return self.count()
  File "/Users/karinawidyastuti/trial/lib/python3.8/site-packages/emailnetwork/extract.py", line 65, in count
    return self.mbox.keys()[-1]+1
IndexError: list index out of range

How to solve this?

**Comment by kwidyas** [comment]
this happen because of my sample mbox. Now, after I pick the right mbox sample, all fine :)
